version: 2
updates:
  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      security-fixes:
        applies-to: security-updates
        patterns:
          - '*'
      gatsby:
        patterns:
          - gatsby
          - gatsby-*
      react:
        patterns:
          - react
          - react-dom
      other-packages:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - '*'
